<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>system_stats_node</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="wujie@todo.todo">wujie</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>glog</depend>
  <depend>mw_base</depend>
  <depend>mw_shm</depend>
  <depend>mw_common</depend>
  <depend>rclcpp</depend>
  <depend>mw_proto_util</depend>
  <depend>system_stats_protos</depend>
  <depend>system_stats_interfaces</depend>
  <depend>diagnostic_msgs</depend>
  <depend>mw_startup</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
